/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "var(--color-on-surface)",
        "outline": "var(--color-outline)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "secondary": "var(--color-secondary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-secondary": "var(--color-on-secondary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-container": "var(--color-on-primary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary": "var(--color-primary)",
        "surface": "var(--color-surface)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-container": "var(--color-surface-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary-container": "var(--color-secondary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        "error-container": "var(--color-error-container)",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "background": "var(--color-background)",
        "surface-dim": "var(--color-surface-dim)",
        "error": "var(--color-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-background": "var(--color-on-background)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-error": "var(--color-on-error)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "lg": "48px",
        "container-max": "1200px",
        "xs": "8px",
        "gutter": "24px",
        "md": "24px",
        "xl": "80px",
        "sm": "16px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["Plus Jakarta Sans"],
        "display-xl": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["36px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "display-xl-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-xl": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
